variable "rds_engine_postgress" {}
variable "rds_engine_version_postgress" {}
variable "rds_port_postgress" {}
variable "vpc_id" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "rds_admin_username_postgress" {}
variable "rds_admin_password_postgress" {}
variable "rds_backup_window" {}
variable "rds_maintenance_window" {}
variable "rds_db_instance_class_postgress" {}
variable "rds_parameter_group_family" {}
variable "public_subnets_cidr" {}
variable "private_subnets_cidr" {}
variable "rds_allocated_storage_postgress" {}
variable "rds_parameter_group_family_postgress" {}