apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-app
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
